### ISSUE TITLE
compile error using the latest  VisualScriptEngine(0.5.0)

### ISSUE THREAD

**Issue by liuyazui** [kovacsv/VisualScriptEngineWxWidgets#1]
compile error using the latest  VisualScriptEngine(0.5.0)

**Comment by kovacsv** [comment]
The wxWidgets port always works with the current version of master branch of VisualScriptEngine. Now I created a tag for the version that works with VSE 0.5.0: https://github.com/kovacsv/VisualScriptEngineWxWidgets/releases/tag/vse-0.5.0. This one should work with the release.

**Comment by liuyazui** [comment]
Thank you very much. It works.
