### ISSUE TITLE
Mind Giving Me The Version 0.0.1

### ISSUE THREAD

**Issue by MichaelZhou-New** [kovacsv/VisualScriptEngineWxWidgets#3]
Hi，

It needs the Version 0.0.1 while compiling the VisualScriptCAD（https://github.com/kovacsv/VisualScriptCAD）. 

Could you mind giving me the Version 0.0.1.

Thanks
Best Regards!
Michael

**Comment by MichaelZhou-New** [comment]
I've got the version of VisualScriptEngineWxWidgets, and then I've got the VisualScriptCAD successfully.

Thanks,
Michael

**Comment by kovacsv** [comment]
Sorry for the late answer. This script should get the version that is needed to compile VisualScriptCAD:
https://github.com/kovacsv/VisualScriptCAD/blob/master/installdepswin.py
